name: Run main.py Daily  

on:  
  schedule:  
    - cron: '0 6 * * *'  # Runs at 06:00 UTC (08:00 CEST)  
  workflow_dispatch:  # Allows manual execution  

permissions:
  contents: write

jobs:  
  run-script:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  

      - name: Set Up Python  
        uses: actions/setup-python@v5  
        with:  
          python-version: '3.11'  

      - name: Install Dependencies  
        run: |  
          pip install -r requirements.txt  

      - name: Run Script and Generate Output with UTF-8 Encoding
        run: |
          python -c "import sys; sys.stdout.reconfigure(encoding='utf-8'); exec(open('main.py').read())" > output.txt
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit File Changes
        run: |
          git config --global user.name 'lalutir'
          git config --global user.email ${{ secrets.EMAIL }}
          git add .
          git commit -m 'commit modified files after automatic run'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Email  
        uses: dawidd6/action-send-mail@v3  
        with:  
          server_address: smtp.gmail.com  
          server_port: 587  
          username: ${{ secrets.EMAIL_USER }}  
          password: ${{ secrets.EMAIL_PASS }}  
          subject: "Daily Report"  
          body: "See attached output."  
          to: ${{ secrets.EMAIL }}  
          from: ${{ secrets.EMAIL }} 
          attachments: output.txt  # Adjust if needed  
