name: Run main.py Daily  

on:  
  schedule:  
    - cron: '0 6 * * *'  # Runs at 06:00 UTC (08:00 CEST)  
  workflow_dispatch:  # Allows manual execution  

permissions:
  contents: write

jobs:  
  run-script:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  

      - name: Set Up Python  
        uses: actions/setup-python@v5  
        with:  
          python-version: '3.11'  

      - name: Install Dependencies  
        run: |  
          pip install -r requirements.txt  

      - name: Run Script and Generate Output with UTF-8 Encoding
        run: |
          python main.py > output.txt
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit File Changes
        run: |
          git config --global user.name 'lalutir'
          git config --global user.email ${{ secrets.EMAIL }}
          git add .
          git commit -m 'commit modified files after automatic run'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Output Content
        id: read_output
        run: echo "OUTPUT_CONTENT<<EOF" >> $GITHUB_ENV && cat output.txt >> $GITHUB_ENV && echo "EOF" >> $GITHUB_ENV

      - name: Find Latest Visualization
        id: find_plot
        run: echo "LATEST_PLOT=$(ls - t Visualizations/Prediction_graph_*.png | head -1)" >> $GITHUB_ENV

      - name: Format Email Subject
        id: format_subject
        run: echo "EMAIL_SUBJECT=📊 Daily Report Predictions for $(date + '%d-%m-%Y')" >> $GITHUB_ENV

      - name: Send Email with Attachment
        uses: dawidd6/action-send-mail@v3  
        with:  
          server_address: smtp.gmail.com  
          server_port: 587  
          username: ${{ secrets.EMAIL_USER }}  
          password: ${{ secrets.EMAIL_PASS }}  
          subject: "${{ env.EMAIL_SUBJECT }}"
          content_type: text/html
          body: |
            <html>
            <body style="font-family: Arial, sans-serif; color: #333;">
              <h2>📊 Daily Report: Predictions for $(date +'%d-%m-%Y')</h2>
                <p>Hello,</p>
                <p>Here is the daily report for <strong>$(date +'%d-%m-%Y')</strong>.</p>

              <h3>🔹 Summary of Predictions:</h3>
              <pre style="background: #f4f4f4; padding: 10px; border-radius: 5px;">${{ env.OUTPUT_CONTENT }}</pre>

              <h3>📎 Attachments:</h3>
              <ul>
                <li>📄 <strong>output.txt</strong> (Full output)</li>
                <li>📈 <strong>Prediction Graph</strong> (Visualization)</li>
              </ul>
            
              <p>Best,</p>
              <p><strong>Automated Report System 🤖</strong></p>
            </body>
            </html> 
          to: ${{ secrets.EMAIL }}  
          from: ${{ secrets.EMAIL }} 
          attachments: output.txt, ${{ env.LATEST_PLOT }}  # Adjust if needed  
