name: Test Run main.py Daily  

on:  
  workflow_dispatch:  # Allows manual execution  

permissions:
  contents: write

jobs:  
  run-script:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  

      - name: Set Up Python  
        uses: actions/setup-python@v5  
        with:  
          python-version: '3.11.1'  

      - name: Install Dependencies  
        run: |  
          pip install -r requirements.txt  

      - name: Run Script and Generate Output with UTF-8 Encoding
        run: |
          cd Code
          python main.py > output.txt 2>&1
          cat output.txt
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit File Changes
        run: |
          git config --global user.name 'lalutir'
          git config --global user.email ${{ secrets.EMAIL_COMMIT }}
          git pull origin main --rebase
          git add .
          git commit -m 'commit modified files after automatic run'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Output Content
        id: read_output
        run: echo "OUTPUT_CONTENT<<EOF" >> $GITHUB_ENV && cat Code/output.txt >> $GITHUB_ENV && echo "EOF" >> $GITHUB_ENV

      - name: Find Latest Visualization
        id: find_plot
        run: echo "LATEST_PLOT=$(ls -t Code/Visualizations/Prediction_graph_*.png | head -1)" >> $GITHUB_ENV

      - name: Set Date
        id: set_date
        run: echo "CURRENT_DATE=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

      - name: Send Email with Attachment
        uses: dawidd6/action-send-mail@v3  
        with:  
          server_address: smtp.gmail.com  
          server_port: 587  
          username: ${{ secrets.EMAIL }}  
          password: ${{ secrets.EMAIL_PASS }}  
          subject: "📊 S&P500 Predictions Daily Report: ${{ env.CURRENT_DATE }}"
          body: |
                Hello, 
                Here is the daily report for the S&P500 predictions for ${{ env.CURRENT_DATE }}.

                📎 Attachments:
                📄 output.txt (Full output)
                📈 Prediction Graph (Visualization)
            
                Best,
                Automated Report System 🤖  
          from: "Automated Report System <${{ secrets.EMAIL }}>" 
          bcc: ${{ vars.EMAIL_COMMIT }}
          attachments: Code/output.txt, ${{ env.LATEST_PLOT }}  # Adjust if needed  
